parameters:
    darvin_crawler.command.crawl.class: Darvin\CrawlerBundle\Command\CrawlCommand

services:
    darvin_crawler.command.crawl:
        class: '%darvin_crawler.command.crawl.class%'
        arguments:
            - '@darvin_crawler.crawler'
            - '%darvin_crawler.uri%'
        tags:
            - { name: console.command }
