parameters:
    darvin_crawler.crawler.class: Darvin\CrawlerBundle\Crawler\Crawler

services:
    Darvin\CrawlerBundle\Crawler\CrawlerInterface: '@darvin_crawler.crawler'

    darvin_crawler.crawler:
        class: '%darvin_crawler.crawler.class%'
        arguments:
            - '@darvin_crawler.http.client'
            - '%darvin_crawler.blacklists.parse%'
            - '%darvin_crawler.blacklists.visit%'
